collections:
  - name: "content"
    label: "კონტენტი"
    files:
      - name: "products_list"
        label: "პროდუქტები"
        file: "data/products.json" # აქ მიუთითებ კონკრეტულ ფაილს
        fields:
          - name: "products"
            label: "პროდუქტების სია"
            widget: "list"
            fields:
              - {label: "დასახელება", name: "title", widget: "string"}
              - {label: "ფასი", name: "price", widget: "string"}
              - {label: "აღწერა", name: "description", widget: "text"}
              - {label: "სურათი", name: "image", widget: "image"}
