backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "პროდუქტები"
    folder: "data"
    create: true
    extension: "json"
    format: "json"
    slug: "{{title}}"
    fields:
      - {label: "დასახელება", name: "title", widget: "string"}
      - {label: "ფასი", name: "price", widget: "string"}
      - {label: "მოკლე აღწერა (ბარათზე)", name: "description", widget: "string"}
      - {label: "სრული ინფორმაცია (მოდალში)", name: "modal_info", widget: "text"}
      - {label: "სურათი", name: "image", widget: "image"}
